name: CI

on:
  issues: {types: opened}


jobs:
  submit-to-trello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.2.0
        with:
          github-token: ${{github.token}}
          script: |
            console.log(process.env.GITHUB_EVENT_PATH)
